runtime: nodejs20
env: standard

instance_class: F1
env_variables:
  MONGO_URI: input you env variables
  JWT_SECRET: input you env variables
  GEMINI_API_KEY: input you env variables
  GEMINI_CHAT_API_KEY: input you env variables
  PORT: "8080"
  ONNXRUNTIME_EXECUTION_PROVIDERS: "cpu"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic

handlers:
  - url: /uploads
    static_dir: uploads
    secure: always

  - url: /.*
    script: auto
    secure: always

inbound_services:
  - warmup 
