runtime: nodejs20
env: standard

instance_class: F1
env_variables:
  MONGO_URI: "mongodb+srv://pratyushmalviya2025:pmukIbKPFPNiRfoS@foodlens.uqadoqk.mongodb.net/"
  JWT_SECRET: "684ffad3b3853448585d93132902034834c9fd949ad4348c4efd00bfc6b21afc03e8b1d5fb829611cbdb8c37ec4896176bdf6830da4dbf92c00cd69262dfc27dc"
  GEMINI_API_KEY: "AIzaSyCx6-K9LqBKHiB3eLSt0q3Zcq-jGSNmJXg"
  GEMINI_CHAT_API_KEY: "AIzaSyA5PyQQmQhaScBchrPgBh3eVbNBLWu83JE"
  NODE_ENV: "production"
  PORT: "8080"
  ONNXRUNTIME_EXECUTION_PROVIDERS: "cpu"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic

handlers:
  - url: /uploads
    static_dir: uploads
    secure: always

  - url: /.*
    script: auto
    secure: always

inbound_services:
  - warmup 